dependencies:
- name: elasticsearch
  version: "0.1.5"
  repository: https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts/
- name: fluent-bit
  version: "1.9.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: elasticsearch-curator
  version: "1.2.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kibana
  version: "2.0.0"
  repository: https://kubernetes-charts.storage.googleapis.com/

